apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sample-fastapi-app
  labels:
    app.kubernetes.io/name: sample-fastapi-app
    release: prometheus
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/name: sample-fastapi-app
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
