apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-fastapi-app-config
  labels:
    app.kubernetes.io/name: sample-fastapi-app
data:
  APP_NAME: sample-fastapi-app
  APP_ENV: production
  APP_VERSION: 1.0.0
  LOG_LEVEL: INFO
